### ISSUE TITLE
Skins with patterns for multiple knives don't say for which knife after the name

### ISSUE THREAD

**Issue by alster551** [adamb70/CSGO-skin-ID-dumper#1]
More of a suggestion than issue, but say its outputting th new "Lore" skin - it names it as "Lore" and not "Lore - Karambit" per se. It could be useful if you could add it in so its clearer which weapon the ID is for?

**Comment by adamb70** [comment]
This is beyond the scope I intended for this script really, but you could try taking the `name` attribute for the skin and appending it to the output for that item.

The information for the flip knife lore skin in `items_game.txt` looks like this. 

    "559"
		{
			"name"		"cu_flip_lore"
			"description_string"		"#Paintkit_cu_lore"
			"description_tag"		"#Paintkit_cu_lore_Tag"
			"style"		"7"
			"pattern"		"flip_lore"
			"pattern_scale"		"1.000000"
			"phongexponent"		"255"
			"phongintensity"		"50"
			"ignore_weapon_size_scale"		"1"
			"only_first_material"		"0"
			"pattern_offset_x_start"		"0.000000"
			"pattern_offset_x_end"		"0.000000"
			"pattern_offset_y_start"		"0.000000"
			"pattern_offset_y_end"		"0.000000"
			"pattern_rotate_start"		"0.000000"
			"pattern_rotate_end"		"0.000000"
			"wear_remap_min"		"0.000000"
			"wear_remap_max"		"0.650000"
		}

The `name` attribute shows `cu_flip_lore`, so you could add this to the output and you would know it was the flip knife. The problem comes when you get a skin with a `name` that isn't very descriptive, like the mac 10 palm skin.

    "201"
		{
			"name"		"sp_palm_bravo"
			"description_string"		"#PaintKit_sp_palm_bravo"
			"description_tag"		"#PaintKit_sp_palm_Tag"
			"pattern"		"palm"
			"wear_default"		"0.350000"
			"style"		"3"
			"color0"		"189 179 155"
			"color1"		"67 74 28"
			"color2"		"87 67 49"
			"color3"		"60 48 38"
			"phongintensity"		"10"
			"pattern_scale"		"1"
			"pattern_offset_x_start"		"0"
			"pattern_offset_x_end"		"1"
			"pattern_offset_y_start"		"0"
			"pattern_offset_y_end"		"1"
			"pattern_rotate_start"		"0"
			"pattern_rotate_end"		"360"
		}

There's nothing in this data that says it is a mac 10 skin so you would have to cross reference some other source to find that out.

**Comment by alster551** [comment]
That's understandable. As far as I'm aware, for skins that have multiple texture files, the weapon is included in the skin name. It's only really knives and certain skins e.g elite build that is difficult to distinguish between which skin Id is for which gun. I will try to add to your existing code a way to get this to work, and send it you you if you want.

**Comment by adamb70** [comment]
Sure, you can create a pull request if you want and I'll add it in :)
